In [51]:
import numpy as np

CREACIÓN DE ARRAYS

In [52]:
# array 1D
lista = [1,2,3,4,5]
array = np.array(lista)
print(f'array 1D:  {array}')

array 1D:  [1 2 3 4 5]


In [53]:
# array 2D
lista_2d = [[1,2,3],[4,5,6]]
array_2d = np.array(lista_2d)
print(f'array 2D: {array_2d}')

array 2D: [[1 2 3]
 [4 5 6]]


CREACIÓN DE FUNCIONES DE NUMPY

ARRAYS CON FUNCIONES

In [54]:
# array de ceros
array_zeros = np.zeros((3,4)) # 3 filas y 4 columnas
print(f'array de ceros: {array_zeros}') 

# array de unos
array_ones = np.ones((2,3)) # 2 filas y 3 columnas
print(f'array de unos: {array_ones}')

# array con valor contante
array_const = np.full((2,3), 7) # 2 filas y 3 columnas
print(f'array con valor contante: {array_const}')

#matriz identidad
array_eye = np.eye(3) # matriz identidad de 3x3
print(f'matriz identidad: {array_eye}')
 
# secuencia especifica de numeros
array_arange = np.arange(0,10,2) # de 0 a 10 con paso de 2
print(f'secuencia especifica de numeros: {array_arange}')

# secuencia de numeros especificos de elementos
array_linspace = np.linspace(0,1,5) # de 0 a 1 con 5 elementos
print(f'secuencia de numeros especificos de elementos: {array_linspace}')


array de ceros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array de unos: [[1. 1. 1.]
 [1. 1. 1.]]
array con valor contante: [[7 7 7]
 [7 7 7]]
matriz identidad: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
secuencia especifica de numeros: [0 2 4 6 8]
secuencia de numeros especificos de elementos: [0.   0.25 0.5  0.75 1.  ]


ARRAYS ALEATORIOS

In [55]:
#numeros aleatorios
array_random = np.random.random((2,3)) # 2 filas y 3 columnas
print(f'numeros aleatorios: {array_random}')

# numeros aleatorios en un rango
array_random_int = np.random.randint(0,10,(3,3)) # de 0 a 10 con 2 filas y 3 columnas
print(f'numeros aleatorios en un rango: {array_random_int}')

# distribucion normal (gauusiana)
array_normal = np.random.normal(0,1,(2,3)) # media 0, desviacion estandar 1, 2 filas y 3 columnas
print(f'distribucion normal: {array_normal}')

# 

numeros aleatorios: [[0.08084307 0.14013834 0.02482829]
 [0.61201259 0.40507198 0.3601396 ]]
numeros aleatorios en un rango: [[2 3 4]
 [0 9 1]
 [6 6 1]]
distribucion normal: [[-0.68765508 -0.82634482 -0.90707487]
 [ 0.31963395  1.3981348   0.65979014]]


ATRIBUTOS DE ARRAYS

In [56]:
array = np.random.randint(0,10,(3,4,5)) # de 0 a 10 con 3 filas y 3 columnas

#dimensiones
print(f'\ndimensiones: {array.ndim}')

# tamaño en cada dimensión
print(f'\ntamaño de la matriz: {array.shape}')

# numero total de elementos
print(f'\nnumero total de elementos: {array.size}')

# tipo de datos
print(f'\ntipo de datos: {array.dtype}')

# mostrar la primera parte del array
print(f'\nprimera parte del array: \n{array[0]}')



dimensiones: 3

tamaño de la matriz: (3, 4, 5)

numero total de elementos: 60

tipo de datos: int32

primera parte del array: 
[[9 4 7 0 6]
 [6 9 0 8 2]
 [2 3 3 0 1]
 [6 8 1 9 9]]


INDEXACIÓN Y SLICING

In [57]:
array_2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f'array 2D: \n{array_2D}')

# acceder a un elemento
print(f'\nacceder a un elemento : {array_2D[1,2]}') # fila 1, columna 2

#slicing de una fila 
print(f'\nslicing de una fila: {array_2D[0,:]}') # fila 1, todas las columnas

#slice de una columna
print(f'\nslice de una columna: {array_2D[:,1]}') # todas las filas, columna 1

#submatriz
print(f'\nsubmatriz: {array_2D[0:2, 1:3]}') # filas 0 a 2, columnas 1 a 3


array 2D: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

acceder a un elemento : 7

slicing de una fila: [1 2 3 4]

slice de una columna: [ 2  6 10]

submatriz: [[2 3]
 [6 7]]


RESHAPING Y MANIPULACIÓN DE DIMENSIONES

In [58]:
# array 3d
array = np.arange(12)
print(array,'\n')

# reshape 2d
array_2d = array.reshape(3,4) # 3 filas y 4 columnas
print(f'reshape_2D: \n{array_2d}')

# reshape 3d
array_3d = array.reshape(2,3,2) # 2 matrices de 3 filas y 2 columnas
print(f'\nreshape_3D: \n{array_3d}')

# transponer un array (intercambiar filas y columnas)
transposed = array_2d.T
print(f'\ntransponer un array:\n {transposed}') # transponer un array (intercambiar filas y columnas)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

reshape_2D: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape_3D: 
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

transponer un array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


VECTORIZACIÓN DE ARREGLOS

In [59]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# suma
print(f'\nsuma: {a+b}') # suma de arrays
print(f'suma: {np.add(a,b)}') # add 

# resta
print(f'\nresta : {a-b}')
print(f'resta: {np.subtract(a,b)}')

# multiplicación 
print(f'\nmultiplicacion: {a*b}')
print(f'multiplicación: {np.multiply(a,b)}')

# división
print(f'\ndivision: {a/b}')
print(f'division: {np.divide(a,b)}')   

# potencia 
print(f'\npotencia: {a**2}')
print(f'potencia: {np.power(a,2)}') 

# raiz cuadrada
print(f'\nraiz cuadrada: {np.sqrt(a)}') # raiz cuadrada de cada elemento
print(f'raiz cuadrada: {np.sqrt(b)}') # raiz cuadrada de cada elemento


suma: [ 6  8 10 12]
suma: [ 6  8 10 12]

resta : [-4 -4 -4 -4]
resta: [-4 -4 -4 -4]

multiplicacion: [ 5 12 21 32]
multiplicación: [ 5 12 21 32]

division: [0.2        0.33333333 0.42857143 0.5       ]
division: [0.2        0.33333333 0.42857143 0.5       ]

potencia: [ 1  4  9 16]
potencia: [ 1  4  9 16]

raiz cuadrada: [1.         1.41421356 1.73205081 2.        ]
raiz cuadrada: [2.23606798 2.44948974 2.64575131 2.82842712]


COMPARACIÓN DE RENDIMIENTO

In [60]:
import time


In [61]:
size = 1000000
date_list = list(range(size))
date_array = np.array(date_list)

# python puro 
start = time.time()
sum_python = sum(date_list)
time_python = time.time() - start
print(f'python puro: {time_python:.6f} segundos')

# numpy
start = time.time()
sum_numpy = np.sum(date_array)
time_np = time.time() - start 
print(f'numpy: {time_python:.6f} segundos')

# comparación
print(f'numpy es {time_python/time_np:.2f} veces más rápido que python puro')


python puro: 0.010996 segundos
numpy: 0.010996 segundos
numpy es 11.00 veces más rápido que python puro


BROADCASTING

Realizar operaciones entre arrays de diferentes formas

In [62]:
# array 2d (matriz)
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'array 2d: \n{array_2d}\n')

# array 1d (vector)
vector = np.array([10,20,30])
print(f'array 1d: {vector}')

# broadcasting: sumar el vector a cada fila de la matriz
result = array_2d + vector
print(f'\nresultado de la suma: \n{result}') # resultado de la suma

array 2d: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

array 1d: [10 20 30]

resultado de la suma: 
[[11 22 33]
 [14 25 36]
 [17 28 39]]


FUNCIONES UNIVERSALES (UNFUNCS)

In [63]:
a = np.array([-1,0,1,2])

# funciones matemáticas
print(np.abs(a)) # valor absoluto
print(np.sin(a)) # seno
print(np.exp(a)) # exponencial
print(np.sqrt(np.abs(a))) # raiz cuadrada
print(np.mean(a)) # media
print(np.std(a)) # desviación estándar

# funciones lógicas
print(a > 0) # mayor que 0
print(np.logical_and(a > 0, a < 2)) # and
print(np.logical_or(a > 0, a < 2)) # or
print(np.less(a, 0)) # menor que 0




[1 0 1 2]
[-0.84147098  0.          0.84147098  0.90929743]
[0.36787944 1.         2.71828183 7.3890561 ]
[1.         0.         1.         1.41421356]
0.5
1.118033988749895
[False False  True  True]
[False False  True False]
[ True  True  True  True]
[ True False False False]


Matemáticas

- add, substract, mltiply, divide
- sqtr, exp, log, power
- sin, cos, tan
- floor, ceil, round

Comparación

- greatel greater_iqual
- less, less_equal
- equal, not_equal
- logical_and, logical_or 

FUNCIONES  MATEMÁTICAS Y ESTADÍSTICAS

In [64]:
array = np.array([[1,2,3],[4,5,6]])

# sumar todos los elementos
print(f'suma total: {np.sum(array)}')

# minimo y maximo
print(f'minimo: {np.min(array)}')
print(f'máximo: {np.max(array)}')

# producto de todos los elementos
print(f'producto total: {np.prod(array)}') # 1 * 2 * 3 * 4 * 5 * 6 = 720

# promedio
print(f'promedio: {np.mean(array)}') # (1+2+3+4+5+6)/6 = 3.5

# mediana
print(f'mediana: {np.median(array)}') # 3.5

# desviacion estandar
print(f'desviacion estandar: {np.std(array)}') # 1.7078

# varianza
print(f'varianza: {np.var(array)}') # 2.915


suma total: 21
minimo: 1
máximo: 6
producto total: 720
promedio: 3.5
mediana: 3.5
desviacion estandar: 1.707825127659933
varianza: 2.9166666666666665


OPERACIONES POR EJES

In [65]:
array = np.array([[1,2,3],[4,5,6]])

# sumar por filas (eje 1)
print(f'suma por filas: {np.sum(array, axis=1)}') # [6 15]

# sumar por columnas (eje 0)
print(f'suma por columnas: {np.sum(array, axis=0)}') # [5 7 9]

# maximo por filas (eje 1)
print(f'máximo por filas: {np.max(array, axis=1)}') # [3 6]

suma por filas: [ 6 15]
suma por columnas: [5 7 9]
máximo por filas: [3 6]


CASO PRÁCTICO: ANÁLISIS DE TEMPERATURAS

In [66]:
# temperaturas ,medias mensuales en grados Celsius para una ciudad
temperaturas = np.array([
    [10,12,15,18,28,23,25,24,22,18,14,11], # año 2022
    [9,11,14,17,21,24,26,25,21,17,13,10], # año 2023
    [10,13,15,19,22,25,27,26,23,19,15,12] # año 2024
])

# nombre de los meses para referencia
meses = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
anio = [2022, 2023, 2024]

# analisis básico
print(f'\nTemperaturas media global: \n{np.mean(temperaturas): .1f}ºC') # 
print(f'\nTemperaturas máxima registrada: \n{np.max(temperaturas): .1f}ºC') # 
print(f'\nTemperaturas media global: \n{np.min(temperaturas): .1f}ºC') # 

 


Temperaturas media global: 
 18.2ºC

Temperaturas máxima registrada: 
 28.0ºC

Temperaturas media global: 
 9.0ºC


TEMPERATURA MEDIA POR MES

In [67]:
# temperatura media por mes 
media_temp_mes = np.mean(temperaturas, axis=0) # minimo por columnas
print(f'\nTemperatura media por mes: \n') # temperatura media por mes
for i, mes in enumerate(meses):
    print(f'{mes}: {media_temp_mes[i]:.1f}ºC') # temperatura media por mes
    


Temperatura media por mes: 

Ene: 9.7ºC
Feb: 12.0ºC
Mar: 14.7ºC
Abr: 18.0ºC
May: 23.7ºC
Jun: 24.0ºC
Jul: 26.0ºC
Ago: 25.0ºC
Sep: 22.0ºC
Oct: 18.0ºC
Nov: 14.0ºC
Dic: 11.0ºC


TEMPERATURA MAXIMA Y MÍNIMA POR MES

In [68]:
# mes mas cálido
mes_calido = np.argmax(np.mean(temperaturas, axis=0)) # mes mas calido
print(f'\nMes más cálido: {meses[mes_calido]} ({media_temp_mes[mes_calido]:.1f}ºC)') # mes mas calido


Mes más cálido: Jul (26.0ºC)


In [69]:
mes_frio = np.argmin(np.mean(temperaturas, axis=0)) # mes mas frio
print(f'\nMes más frío: {meses[mes_frio]} ({media_temp_mes[mes_frio]:.1f}ºC)') # mes mas frio


Mes más frío: Ene (9.7ºC)


TEMPERATURA MEDIA POR AÑO

In [70]:
# temperaturas media por año
media_temp_anio = np.mean(temperaturas, axis=1) # temperatura media por año
print(f'\nTemperatura media por año: \n') # temperatura media por año
for i, temp in enumerate(media_temp_anio):
    print(f'Año {anio[i]}: {temp:.1f}ºC') 
    
    


Temperatura media por año: 

Año 2022: 18.3ºC
Año 2023: 17.3ºC
Año 2024: 18.8ºC


AÑO MAS CÁLIDO

In [ ]:
# Año mas cálido
anio_calido = np.argmax(np.mean(temperaturas, axis=1)) # año mas calido
print(f'\nAño más cálido: {anio[anio_calido]} ({media_temp_anio[anio_calido]:.1f}ºC)') # año mas calido


Año más cálido: 2024 (18.8ºC)


In [72]:
# variación de temperaturas
variacion_temp = np.std(temperaturas, axis=0) # variacion de temperaturas
print(f'\nVariación de temperaturas por mes: \n') # variacion de temperaturas
for i, mes in enumerate(meses):
    print(f'{mes}: {variacion_temp[i]:.1f}ºC') # variacion de temperaturas


Variación de temperaturas por mes: 

Ene: 0.5ºC
Feb: 0.8ºC
Mar: 0.5ºC
Abr: 0.8ºC
May: 3.1ºC
Jun: 0.8ºC
Jul: 0.8ºC
Ago: 0.8ºC
Sep: 0.8ºC
Oct: 0.8ºC
Nov: 0.8ºC
Dic: 0.8ºC
