In [1]:
import numpy as np

CREACIÓN DE ARRAYS

In [2]:
# array 1D
lista = [1,2,3,4,5]
array = np.array(lista)
print(f'array 1D:  {array}')

array 1D:  [1 2 3 4 5]


In [3]:
# array 2D
lista_2d = [[1,2,3],[4,5,6]]
array_2d = np.array(lista_2d)
print(f'array 2D: {array_2d}')

array 2D: [[1 2 3]
 [4 5 6]]


CREACIÓN DE FUNCIONES DE NUMPY

ARRAYS CON FUNCIONES

In [4]:
# array de ceros
array_zeros = np.zeros((3,4)) # 3 filas y 4 columnas
print(f'array de ceros: {array_zeros}') 

# array de unos
array_ones = np.ones((2,3)) # 2 filas y 3 columnas
print(f'array de unos: {array_ones}')

# array con valor contante
array_const = np.full((2,3), 7) # 2 filas y 3 columnas
print(f'array con valor contante: {array_const}')

#matriz identidad
array_eye = np.eye(3) # matriz identidad de 3x3
print(f'matriz identidad: {array_eye}')
 
# secuencia especifica de numeros
array_arange = np.arange(0,10,2) # de 0 a 10 con paso de 2
print(f'secuencia especifica de numeros: {array_arange}')

# secuencia de numeros especificos de elementos
array_linspace = np.linspace(0,1,5) # de 0 a 1 con 5 elementos
print(f'secuencia de numeros especificos de elementos: {array_linspace}')


array de ceros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array de unos: [[1. 1. 1.]
 [1. 1. 1.]]
array con valor contante: [[7 7 7]
 [7 7 7]]
matriz identidad: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
secuencia especifica de numeros: [0 2 4 6 8]
secuencia de numeros especificos de elementos: [0.   0.25 0.5  0.75 1.  ]


ARRAYS ALEATORIOS

In [5]:
#numeros aleatorios
array_random = np.random.random((2,3)) # 2 filas y 3 columnas
print(f'numeros aleatorios: {array_random}')

# numeros aleatorios en un rango
array_random_int = np.random.randint(0,10,(3,3)) # de 0 a 10 con 2 filas y 3 columnas
print(f'numeros aleatorios en un rango: {array_random_int}')

# distribucion normal (gauusiana)
array_normal = np.random.normal(0,1,(2,3)) # media 0, desviacion estandar 1, 2 filas y 3 columnas
print(f'distribucion normal: {array_normal}')

# 

numeros aleatorios: [[0.49535683 0.49554311 0.79829283]
 [0.54927386 0.72884699 0.96108738]]
numeros aleatorios en un rango: [[3 6 2]
 [2 1 0]
 [4 6 3]]
distribucion normal: [[ 1.03990501 -0.06377525  0.13194539]
 [-0.3673252   0.43975723 -0.72712521]]


ATRIBUTOS DE ARRAYS

In [34]:
array = np.random.randint(0,10,(3,4,5)) # de 0 a 10 con 3 filas y 3 columnas

#dimensiones
print(f'\ndimensiones: {array.ndim}')

# tamaño en cada dimensión
print(f'\ntamaño de la matriz: {array.shape}')

# numero total de elementos
print(f'\nnumero total de elementos: {array.size}')

# tipo de datos
print(f'\ntipo de datos: {array.dtype}')

# mostrar la primera parte del array
print(f'\nprimera parte del array: \n{array[0]}')



dimensiones: 3

tamaño de la matriz: (3, 4, 5)

numero total de elementos: 60

tipo de datos: int32

primera parte del array: 
[[7 2 1 1 2]
 [7 0 2 6 1]
 [8 1 0 6 6]
 [4 1 4 5 8]]


INDEXACIÓN Y SLICING

In [7]:
array_2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f'array 2D: \n{array_2D}')

# acceder a un elemento
print(f'\nacceder a un elemento : {array_2D[1,2]}') # fila 1, columna 2

#slicing de una fila 
print(f'\nslicing de una fila: {array_2D[0,:]}') # fila 1, todas las columnas

#slice de una columna
print(f'\nslice de una columna: {array_2D[:,1]}') # todas las filas, columna 1

#submatriz
print(f'\nsubmatriz: {array_2D[0:2, 1:3]}') # filas 0 a 2, columnas 1 a 3


array 2D: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

acceder a un elemento : 7

slicing de una fila: [1 2 3 4]

slice de una columna: [ 2  6 10]

submatriz: [[2 3]
 [6 7]]


RESHAPING Y MANIPULACIÓN DE DIMENSIONES

In [9]:
# array 3d
array = np.arange(12)
print(array,'\n')

# reshape 2d
array_2d = array.reshape(3,4) # 3 filas y 4 columnas
print(f'reshape_2D: \n{array_2d}')

# reshape 3d
array_3d = array.reshape(2,3,2) # 2 matrices de 3 filas y 2 columnas
print(f'\nreshape_3D: \n{array_3d}')

# transponer un array (intercambiar filas y columnas)
transposed = array_2d.T
print(f'\ntransponer un array:\n {transposed}') # transponer un array (intercambiar filas y columnas)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

reshape_2D: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape_3D: 
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

transponer un array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


VECTORIZACIÓN DE ARREGLOS

In [19]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# suma
print(f'\nsuma: {a+b}') # suma de arrays
print(f'suma: {np.add(a,b)}') # add 

# resta
print(f'\nresta : {a-b}')
print(f'resta: {np.subtract(a,b)}')

# multiplicación 
print(f'\nmultiplicacion: {a*b}')
print(f'multiplicación: {np.multiply(a,b)}')

# división
print(f'\ndivision: {a/b}')
print(f'division: {np.divide(a,b)}')   

# potencia 
print(f'\npotencia: {a**2}')
print(f'potencia: {np.power(a,2)}') 

# raiz cuadrada
print(f'\nraiz cuadrada: {np.sqrt(a)}') # raiz cuadrada de cada elemento
print(f'raiz cuadrada: {np.sqrt(b)}') # raiz cuadrada de cada elemento


suma: [ 6  8 10 12]
suma: [ 6  8 10 12]

resta : [-4 -4 -4 -4]
resta: [-4 -4 -4 -4]

multiplicacion: [ 5 12 21 32]
multiplicación: [ 5 12 21 32]

division: [0.2        0.33333333 0.42857143 0.5       ]
division: [0.2        0.33333333 0.42857143 0.5       ]

potencia: [ 1  4  9 16]
potencia: [ 1  4  9 16]

raiz cuadrada: [1.         1.41421356 1.73205081 2.        ]
raiz cuadrada: [2.23606798 2.44948974 2.64575131 2.82842712]


COMPARACIÓN DE RENDIMIENTO

In [ ]:
import time


In [ ]:
size = 1000000
date_list = list(range(size))
date_array = np.array(date_list)

# python puro 
start = time.time()
sum_python = sum(date_list)
time_python = time.time() - start
print(f'python puro: {time_python:.6f} segundos')

# numpy
start = time.time()
sum_numpy = np.sum(date_array)
time_np = time.time() - start 
print(f'numpy: {time_python:.6f} segundos')

# comparación
print(f'numpy es {time_python/time_np:.2f} veces más rápido que python puro')


python puro: 0.008994 segundos
numpy: 0.008994 segundos
numpy es 4.51 veces más rápido que python puro


BROADCASTING

Realizar operaciones entre arrays de diferentes formas

In [32]:
# array 2d (matriz)
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'array 2d: \n{array_2d}\n')

# array 1d (vector)
vector = np.array([10,20,30])
print(f'array 1d: {vector}')

# broadcasting: sumar el vector a cada fila de la matriz
result = array_2d + vector
print(f'\nresultado de la suma: \n{result}') # resultado de la suma

array 2d: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

array 1d: [10 20 30]

resultado de la suma: 
[[11 22 33]
 [14 25 36]
 [17 28 39]]


FUNCIONES UNIVERSALES (UNFUNCS)

In [38]:
a = np.array([-1,0,1,2])

# funciones matemáticas
print(np.abs(a)) # valor absoluto
print(np.sin(a)) # seno
print(np.exp(a)) # exponencial
print(np.sqrt(np.abs(a))) # raiz cuadrada
print(np.mean(a)) # media
print(np.std(a)) # desviación estándar

# funciones lógicas
print(a > 0) # mayor que 0
print(np.logical_and(a > 0, a < 2)) # and
print(np.logical_or(a > 0, a < 2)) # or
print(np.less(a, 0)) # menor que 0




[1 0 1 2]
[-0.84147098  0.          0.84147098  0.90929743]
[0.36787944 1.         2.71828183 7.3890561 ]
[1.         0.         1.         1.41421356]
0.5
1.118033988749895
[False False  True  True]
[False False  True False]
[ True  True  True  True]
[ True False False False]


Matemáticas

- add, substract, mltiply, divide
- sqtr, exp, log, power
- sin, cos, tan
- floor, ceil, round

Comparación

- greatel greater_iqual
- less, less_equal
- equal, not_equal
- logical_and, logical_or 

FUNCIONES  MATEMÁTICAS Y ESTADÍSTICAS