In [2]:
import numpy as np

CREACIÓN DE ARRAYS

In [3]:
# array 1D
lista = [1,2,3,4,5]
array = np.array(lista)
print(f'array 1D:  {array}')

array 1D:  [1 2 3 4 5]


In [4]:
# array 2D
lista_2d = [[1,2,3],[4,5,6]]
array_2d = np.array(lista_2d)
print(f'array 2D: {array_2d}')

array 2D: [[1 2 3]
 [4 5 6]]


CREACIÓN DE FUNCIONES DE NUMPY

ARRAYS CON FUNCIONES

In [5]:
# array de ceros
array_zeros = np.zeros((3,4)) # 3 filas y 4 columnas
print(f'array de ceros: {array_zeros}') 

# array de unos
array_ones = np.ones((2,3)) # 2 filas y 3 columnas
print(f'array de unos: {array_ones}')

# array con valor contante
array_const = np.full((2,3), 7) # 2 filas y 3 columnas
print(f'array con valor contante: {array_const}')

#matriz identidad
array_eye = np.eye(3) # matriz identidad de 3x3
print(f'matriz identidad: {array_eye}')
 
# secuencia especifica de numeros
array_arange = np.arange(0,10,2) # de 0 a 10 con paso de 2
print(f'secuencia especifica de numeros: {array_arange}')

# secuencia de numeros especificos de elementos
array_linspace = np.linspace(0,1,5) # de 0 a 1 con 5 elementos
print(f'secuencia de numeros especificos de elementos: {array_linspace}')


array de ceros: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array de unos: [[1. 1. 1.]
 [1. 1. 1.]]
array con valor contante: [[7 7 7]
 [7 7 7]]
matriz identidad: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
secuencia especifica de numeros: [0 2 4 6 8]
secuencia de numeros especificos de elementos: [0.   0.25 0.5  0.75 1.  ]


ARRAYS ALEATORIOS

In [6]:
#numeros aleatorios
array_random = np.random.random((2,3)) # 2 filas y 3 columnas
print(f'numeros aleatorios: {array_random}')

# numeros aleatorios en un rango
array_random_int = np.random.randint(0,10,(3,3)) # de 0 a 10 con 2 filas y 3 columnas
print(f'numeros aleatorios en un rango: {array_random_int}')

# distribucion normal (gauusiana)
array_normal = np.random.normal(0,1,(2,3)) # media 0, desviacion estandar 1, 2 filas y 3 columnas
print(f'distribucion normal: {array_normal}')

# 

numeros aleatorios: [[0.54905457 0.32437715 0.91415294]
 [0.6984969  0.1183188  0.66945665]]
numeros aleatorios en un rango: [[7 8 5]
 [3 0 3]
 [2 1 0]]
distribucion normal: [[ 0.88115887  0.34454297 -2.08601002]
 [-0.73323884 -0.91934859 -0.18647424]]


ATRIBUTOS DE ARRAYS

In [7]:
array = np.random.randint(0,10,(3,4,5)) # de 0 a 10 con 3 filas y 3 columnas

#dimensiones
print(f'dimensiones: {array.ndim}')

# tamaño en cada dimensión
print(f'tamaño de la matriz: {array.shape}')

# numero total de elementos
print(f'numero total de elementos: {array.size}')

# tipo de datos
print(f'tipo de datos: {array.dtype}')

# mostrar la primera parte del array
print(f'primera parte del array: {array[0]}')


dimensiones: 3
tamaño de la matriz: (3, 4, 5)
numero total de elementos: 60
tipo de datos: int32
primera parte del array: [[7 3 5 0 7]
 [9 1 4 4 6]
 [0 5 2 7 7]
 [6 1 0 2 1]]


INDEXACIÓN Y SLICING

In [14]:
array_2D = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(f'array 2D: \n{array_2D}')

# acceder a un elemento
print(f'\nacceder a un elemento : {array_2D[1,2]}') # fila 1, columna 2

#slicing de una fila 
print(f'\nslicing de una fila: {array_2D[0,:]}') # fila 1, todas las columnas

#slice de una columna
print(f'\nslice de una columna: {array_2D[:,1]}') # todas las filas, columna 1

#submatriz
print(f'\nsubmatriz: {array_2D[0:2, 1:3]}') # filas 0 a 2, columnas 1 a 3


array 2D: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

acceder a un elemento : 7

slicing de una fila: [1 2 3 4]

slice de una columna: [ 2  6 10]

submatriz: [[2 3]
 [6 7]]


RESHAPING Y MANIPULACIÓN DE DIMENSIONES

In [27]:
# array 3d
array = np.arange(12)
print(array,'\n')

# reshape 2d
array_2d = array.reshape(3,4) # 3 filas y 4 columnas
print(f'reshape_2D: \n{array_2d}')

# reshape 3d
array_3d = array.reshape(2,3,2) # 2 matrices de 3 filas y 2 columnas
print(f'reshape_3D: \n{array_3d}')

# transponer un array (intercambiar filas y columnas)
transposed = array_2d.T
print(f'\ntransponer un array:\n {transposed}') # transponer un array (intercambiar filas y columnas)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

reshape_2D: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
reshape_3D: 
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

transponer un array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
